# file: C:\Users\Lisardo Iniesta\AppData\Roaming\Python\Python313\site-packages\urllib3\connection.py
# hypothesis_version: 6.142.1

[b'\n', b'\r\n', b'%x\r\n%b\r\n', b'0\r\n\r\n', b'CONNECT %s:%d HTTP/1.0\r\n', 0.0, 443, 2023, 16384, '%', "', '", '.', 'Content-Length', 'HTTP/?', 'Transfer-Encoding', 'User-Agent', '[]', '[^a-z]', '_http_vsn_str', 'accept-encoding', 'ascii', 'audit', 'before connect', 'chunked', 'content-length', 'h2', 'header line', 'header:', 'host', 'http', 'http.client.connect', 'https', 'latin-1', 'load_default_certs', 'record layer failure', 'transfer-encoding', 'unknown protocol', 'user-agent', 'utf-8', 'wrong version number']